kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: ci-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ci-storage
