identities:
- name: gcp
  gcp:
    encodedServiceAccountKey: $AGENT_ENCODED_KEY
metrics:
- name: requests
  type: int
  aggregation:
    bufferSeconds: 60
  endpoints:
  - name: disk
  - name: servicecontrol
- name: instance_time
  type: int
  aggregation:
    bufferSeconds: 60
  endpoints:
  - name: disk
  - name: servicecontrol
endpoints:
- name: disk
  disk: /opt/persistent/
    reportDir: 
    expireSeconds: 3600
- name: servicecontrol
  servicecontrol:
    identity: gcp
    serviceName: redis-marketplace.googleapis.com
    consumerId: $AGENT_CONSUMER_ID
sources:
- name: instance_time
  heartbeat:
    metric: instance_time
    intervalSeconds: 10
    value:
      int64Value: 10
