apiVersion: "app.redislabs.com/v1alpha1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise"
spec:
  nodes: 3
  serviceBrokerSpec:
    enabled: true
    persistentSpec:
      storageClassName: "gp2"
