apiVersion: "app.redislabs.com/v1alpha1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise"
spec:
  nodes: 3
  serviceBrokerSpec:
    enabled: true
    persistentSpec:
      storageClassName: "gp2"
    imageSpec:
     imagePullPolicy:  Always
     repository:       redislabs/service-broker
     versionTag:       78_4b9b17f.rhel7
  redisEnterpriseImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/redis
    versionTag:       5.4.0-19.rhel7-openshift
  redisEnterpriseServicesRiggerImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/k8s-controller
    versionTag:       109_5c9af60.rhel7

