apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: redis-enterprise-psp
  labels:
    app: redis-enterprise
spec:
  privileged: false
  allowPrivilegeEscalation: false
  allowedCapabilities:
    - SYS_RESOURCE
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1001
      max: 1001
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - '*'
