apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacedvalidatingtypes.app.redislabs.com
  labels:
    app: redis-enterprise
spec:
  group: app.redislabs.com
  names:
    kind: NamespacedValidatingType
    listKind: NamespacedValidatingTypeList
    plural: namespacedvalidatingtypes
    singular: namespacedvalidatingtype
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              types:
                items:
                  properties:
                    apiGroups:
                      items:
                        type: string
                      type: array
                    apiVersions:
                      items:
                        type: string
                      type: array
                    operations:
                      items:
                        type: string
                      type: array
                    resources:
                      items:
                        type: string
                      type: array
                    scope:
                      type: string
                  type: object
                type: array
            type: object
          status:
            properties:
              observedGeneration:
                format: int64
                type: integer
            type: object
        type: object