apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: redis-enterprise
  name: operator-environment-config
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- include "redis-enterprise-operator.annotations" . | nindent 4}}
data:
  {{- with .Values.operator }}
  ACTIVE_ACTIVE_DATABASE_CONTROLLER_ENABLED: {{ .activeActiveDatabaseControllerEnabled | quote }}
  {{- end }}