apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: redis-enterprise
  name: operator-environment-config
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- include "redis-enterprise-operator.annotations" . | nindent 4}}
