apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    annotations:
        redis/helm-chart-ver: {{ .Chart.Version }}
        redis/operator-ver: {{ .Values.operator.image.tag }}
    labels:
        app: redis-enterprise
    name: redis-enterprise-operator
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups:
        - rbac.authorization.k8s.io
        - ""
      resources:
        - roles
        - serviceaccounts
        - rolebindings
      verbs:
        - bind
        - escalate
        - impersonate
        - userextras
        - create
        - get
        - list
        - watch
        - update
        - patch
        - delete
        - deletecollection
    - apiGroups:
        - app.redislabs.com
      resources:
        - redisenterpriseclusters
        - redisenterpriseclusters/status
        - redisenterpriseclusters/finalizers
        - redisenterprisedatabases
        - redisenterprisedatabases/status
        - redisenterprisedatabases/finalizers
        - redisenterpriseremoteclusters
        - redisenterpriseremoteclusters/status
        - redisenterpriseremoteclusters/finalizers
        - redisenterpriseactiveactivedatabases
        - redisenterpriseactiveactivedatabases/status
        - redisenterpriseactiveactivedatabases/finalizers
      verbs:
        - delete
        - deletecollection
        - get
        - list
        - patch
        - create
        - update
        - watch
    - apiGroups:
        - ""
      resources:
        - secrets
      verbs:
        - update
        - get
        - read
        - list
        - listallnamespaces
        - watch
        - watchlist
        - watchlistallnamespaces
        - create
        - patch
        - replace
        - delete
        - deletecollection
    - apiGroups:
        - ""
      resources:
        - endpoints
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - events
      verbs:
        - create
        - patch
    - apiGroups:
        - apps
      resources:
        - deployments
        - statefulsets
        - replicasets
      verbs:
        - create
        - delete
        - deletecollection
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - policy
      resources:
        - poddisruptionbudgets
      verbs:
        - create
        - delete
        - get
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - create
        - delete
        - get
        - update
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - persistentvolumeclaims
      verbs:
        - create
        - delete
        - get
        - update
        - list
        - watch
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - watch
        - list
        - update
        - patch
        - delete
    - apiGroups:
        - ""
      resources:
        - services
      verbs:
        - get
        - watch
        - list
        - update
        - patch
        - create
        - delete
    - apiGroups:
        - policy
      resourceNames:
        - redis-enterprise-psp
      resources:
        - podsecuritypolicies
      verbs:
        - use
    - apiGroups:
        - networking.k8s.io
      resources:
        - ingresses
      verbs:
        - create
        - patch
        - replace
        - delete
        - deletecollection
        - read
        - list
        - listallnamespaces
        - watch
        - watchlist
        - watchlistallnamespaces
        - patchstatus
        - readstatus
        - replacestatus
        - update
    - apiGroups:
        - networking.istio.io
      resources:
        - gateways
        - virtualservices
      verbs:
        - get
        - watch
        - list
        - update
        - patch
        - create
        - delete
	{{- if .Values.isOpenshift }}
    - apiGroups: ["route.openshift.io"]
      resources: ["routes", "routes/custom-host"]
      verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
    - apiGroups: ["security.openshift.io"]
      resourceNames: ["nonroot"]
      resources: ["securitycontextconstraints"]
      verbs: ["use"]
	{{- end }}
