apiVersion: v1
kind: ServiceAccount
metadata:
    annotations:
        {{- include "redis-enterprise-operator.annotations" . | nindent 8}}
    labels:
        app: redis-enterprise
    name: redis-enterprise-operator
