apiVersion: v1
kind: ServiceAccount
metadata:
    annotations:
        redis/helm-chart-ver: {{ .Chart.Version }}
        redis/operator-ver: {{ .Values.operator.image.tag }}
    labels:
        app: redis-enterprise
    name: redis-enterprise-operator
    namespace: {{ .Release.Namespace }}
