
{{ $admissionNamespaces := append (default list .Values.admission.namespaces) .Release.Namespace | uniq}}

{{- $namespaceToCA := dict }}

{{- if .Values.admission.setCABundle }}
  {{- $namespaceToCA = include "redis-enterprise-operator.getCa" $admissionNamespaces | fromYaml }}
  {{- range $ns := $admissionNamespaces }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "redis-enterprise-operator.annotations" $ | nindent 4}}
  name: admission-tls
  namespace: {{ $ns }}
type: Opaque
data:
  cert: {{ dig $ns "cert" "# Missing cert" $namespaceToCA }}
  privateKey: {{ dig $ns "privateKey" "# Missing privateKey" $namespaceToCA}}

---
  {{- end }}
{{- end }}

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    {{- include "redis-enterprise-operator.annotations" . | nindent 4}}
  labels:
    app: redis-enterprise
  name: redis-enterprise-admission
webhooks:
{{- range $ns := $admissionNamespaces }}
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: admission
        path: /admission
        namespace: {{ $ns }}
      {{- if $.Values.admission.setCABundle }}
      caBundle: {{ dig $ns "cert" "# Missing cert" $namespaceToCA}}
      {{- else }}
      caBundle: {{ include "redis-enterprise-operator.caComment" $ | trimAll "\n" }}
      {{- end }}
    failurePolicy: Fail
    matchPolicy: Exact
    name: redisenterprise.admission.redislabs-{{ $ns }}
    {{ if $.Values.admission.limitToNamespace }}
    namespaceSelector:
      matchLabels:
        redis.io/redisenterprise.admission.enable: {{ $ns }}
    {{ end }}
    rules:
      - apiGroups:
          - app.redislabs.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - redisenterprisedatabases
          - redisenterpriseactiveactivedatabases
          - redisenterpriseremoteclusters
    sideEffects: None
    timeoutSeconds: 30
{{- end}}
