{{- $admissionTLSConfig := dict }}

{{- if .Values.admission.setCABundle }}
{{- $admissionTLSConfig = include "redis-enterprise-operator.admissionTLSConfig" . | fromYaml }}
{{- /* Skip secret creation if it was already created by the admission server */ -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "admission-tls") }}
{{- if or (not $secret) (eq (dig "metadata" "labels" "app.kubernetes.io/managed-by" "" $secret) "Helm") }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "redis-enterprise-operator.annotations" . | nindent 4 }}
  name: admission-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cert: {{ get $admissionTLSConfig "cert" }}
  privateKey: {{ get $admissionTLSConfig "privateKey" }}

---
{{- end }}{{- /* if not $secret */ -}}
{{- end }}{{- /* if setCABundle */ -}}

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    {{- include "redis-enterprise-operator.annotations" . | nindent 4}}
  labels:
    app: redis-enterprise
  {{- if $.Values.admission.limitToNamespace }}
  name: redis-enterprise-admission-{{ .Release.Namespace }}
  {{- else }}
  name: redis-enterprise-admission
  {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: admission
        path: /admission
        namespace: {{ .Release.Namespace }}
      {{- if $.Values.admission.setCABundle }}
      caBundle: {{ get $admissionTLSConfig "cert" }}
      {{- else }}
      caBundle: "" # Fill in with BASE64 encoded signed cert
      {{- end }}
    failurePolicy: Fail
    matchPolicy: Exact
    name: redisenterprise.admission.redislabs
    {{- if $.Values.admission.limitToNamespace }}
    namespaceSelector:
      matchLabels:
        redis.io/redisenterprise.admission.enable: {{ .Release.Namespace }}
    {{- end }}
    rules:
      - apiGroups:
          - app.redislabs.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - redisenterprisedatabases
          - redisenterpriseactiveactivedatabases
          - redisenterpriseremoteclusters
    sideEffects: None
    timeoutSeconds: 30
