# This file includes the values that can be customized for the chart.
#
# For instructions how to override these default values,
# see https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing

# Image pull secret to use for registry authentication
imagePullSecrets: null

# Configuration options for the operator
operator:

  # Configuration options for the operator image
  image:

    # Image repository for the operator image.
    # Leave blank to use the default image repository,
    # which is `redislabs/operator` for non-OpenShift deployments,
    # and `registry.connect.redhat.com/redislabs/redis-enterprise-operator` for OpenShift deployments.
    repository: ""

    # Image tag for the operator image.
    # This typically represents the operator version.
    tag: 7.22.0-7

# Configuration options for the admission webhook
admission:

  # Whether to create a new CA key and certificate for the admission webhook
  setCABundle: true

  # Whether to deploy the admission webhook limited to objects in the installation namespace.
  limitToNamespace: true

# Configuration options for OpenShift
openshift:

  # Set to true if deploying to an OpenShift cluster
  mode: false
  
  # Configuration options for the SecurityContextConstraints
  scc:
    
    # Whether to install the SecurityContextConstraints object for Redis Enterprise
    install: false

    # Whether to keep (avoid deleting) the SecurityContextConstraints object when uninstaling the chart.
    # This can be useful if installing the chart multiple times in the cluster, such that the SCC
    # can be shared between multiple chart installations.
    shared: false
