apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseCluster
metadata:
  name: rec
spec:
  persistentSpec:
    storageClassName: standard
    volumeSize: 20Gi
  redisEnterpriseImageSpec:
    repository: [User redis Private repo]
    versionTag: 6.2.10-83
  redisEnterpriseServicesRiggerImageSpec:
    repository: [User service rigger Private repo]
    versionTag: 6.2.10-3
  bootstrapperImageSpec:
    repository: [User operator Private repo]
    versionTag: 6.2.10-3