apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: redb-admission
  labels:
    app: redis-enterprise
webhooks:
- name: redb.admission.redislabs
  failurePolicy: Fail
  matchPolicy: Exact
  sideEffects: None
  timeoutSeconds: 30
  rules:
  - apiGroups:   ["app.redislabs.com"]
    apiVersions: ["v1alpha1"]
    operations:  ["*"]
    resources:   ["redisenterprisedatabases"]
  clientConfig:
    service:
      namespace: NAMESPACE_OF_SERVICE_ACCOUNT
      name: admission
      path: /admission
    caBundle: "" # Fill in with BASE64 encoded signed cert
  admissionReviewVersions: ["v1beta1"]
