apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise"
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: "gp2" # edit according to infrastructure
