apiVersion: "app.redislabs.com/v1alpha1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise-cluster"
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: "gp2"
  serviceBrokerSpec:
    enabled: true
    persistentSpec:
      storageClassName: "gp2"
    imageSpec:
     imagePullPolicy: Always
     repository:      redislabs/service-broker
     versionTag:      39_5bfe271.rhel7
  redisEnterpriseImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/redis
    versionTag:       5.4.0-17.rhel7-openshift
  redisEnterpriseControllerImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/k8s-controller
    versionTag:       65_7e696a1.rhel7
    
