apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseClusterRole
metadata:
  name: cluster-admin
  labels:
    app: redis-enterprise
spec:
  # One of: 
  # Admin, UserManager, ClusterMember, ClusterViewer,
  # DBMember, DBViewer, None.
  managementRole: Admin

  # An optional ACL that applies to all databases in the cluster.
  acl:
    kind: RedisEnterpriseACL
    name: full-access

