apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseRoleBinding
metadata:
  name: db-reader
  labels:
    app: redis-enterprise
spec:
  # A reference to a RedisEnterpriseRole object.
  roleRef:
    kind: RedisEnterpriseRole
    name: db-reader

  # A reference to one or more RedisEnterpriseUser objects,
  # or other kinds of subjects.
  subjects:
  - kind: RedisEnterpriseUser
    name: some-db-user
