identities:
- name: gcp
  gcp:
    encodedServiceAccountKey: $AGENT_ENCODED_KEY
metrics:
- name: instance_time
  type: int
  aggregation:
    bufferSeconds: 60
  endpoints:
  - name: servicecontrol
endpoints:
- name: servicecontrol
  servicecontrol:
    identity: gcp
    serviceName: test-marketplace-whitebox-usage.googleapis.com
    consumerId: $AGENT_CONSUMER_ID
sources:
- name: instance_time
  heartbeat:
    metric: instance_time
    intervalSeconds: 10
    value:
      int64Value: 10

