apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redisenterpriseremoteclusters.app.redislabs.com
spec:
  group: app.redislabs.com
  names:
    kind: RedisEnterpriseRemoteCluster
    listKind: RedisEnterpriseRemoteClusterList
    plural: redisenterpriseremoteclusters
    singular: redisenterpriseremotecluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RedisEntepriseRemoteCluster represents a remote participating cluster.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apiIngressUrl:
              description: The URL of the cluster, will be used for the active-active
                database URL.
              type: string
            dbUrlSuffix:
              description: The database URL suffix, will be used for the active-active
                database replication endpoint and replication endpoint SNI.
              type: string
            name:
              description: 'The name of the remote cluster. Must be of the following
                format: "<REC name>.<REC namespace>".'
              type: string
            secretName:
              description: 'The name of the secret containing cluster credentials.
                Must be of the following format: "redis-enterprise-<REC name>-<REC
                namespace>"'
              type: string
          required:
          - apiIngressUrl
          - name
          type: object
        status:
          properties:
            local:
              description: Indicates whether this object represents a local or a remote
                cluster.
              type: boolean
            specStatus:
              description: Whether the desired specification is valid.
              type: string
            status:
              description: The status of the remote cluster.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
