apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisenterpriseacls.app.redislabs.com
spec:
  group: app.redislabs.com
  names:
    kind: RedisEnterpriseACL
    listKind: RedisEnterpriseACLList
    plural: redisenterpriseacls
    singular: redisenterpriseacl
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RedisEnterpriseACL represents an access control list definition
          for a Redis database.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RedisEnterpriseACLSpec defines the desired state of RedisEnterpriseACL
            properties:
              acl:
                description: Redis ACL rule
                type: string
            type: object
          status:
            description: RedisEnterpriseACLStatus defines the observed state of RedisEnterpriseACL
            properties:
              max_version:
                description: Maximum Redis database version that supports this ACL
                type: string
              min_version:
                description: Minimum Redis database version that supports this ACL
                type: string
              uid:
                description: The internal UID of the Redis ACL object defined in the
                  Redis Enterprise Cluster.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
