kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gesher
  labels:
    app: redis-enterprise
subjects:
- kind: ServiceAccount
  name: gesher
  namespace: NAMESPACE_OF_SERVICE_ACCOUNT
roleRef:
  kind: ClusterRole
  name: gesher
  apiGroup: rbac.authorization.k8s.io
