kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gesher
  labels:
    app: redis-enterprise
subjects:
- kind: ServiceAccount
  name: gesher
roleRef:
  kind: Role
  name: gesher
  apiGroup: rbac.authorization.k8s.io
