apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: redis-enterprise-crds
  annotations:
    "redis/operator-ver": {{ .Values.operator.image.tag }}
    "redis/helm-chart-ver": {{ .Chart.Version }}
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    app: redis-enterprise
spec:
  template:
    metadata:
      labels:
        app: redis-enterprise
    spec:
      serviceAccountName: redis-enterprise-crds
      containers:
        - name: gatekeeper-crds
          image: {{ include "redis-enterprise-operator.operator.image" . | printf "%s" | trim }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
          command:
            - crd-installer
          args:
            - "-action=applyCRD"
            - "-crdPaths=/crds/rec_crd.yaml,/crds/redb_crd.yaml,/crds/reaadb_crd.yaml,/crds/rerc_crd.yaml"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
      restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-enterprise-crds
  annotations:
    "redis/operator-ver": {{ .Values.operator.image.tag }}
    "redis/helm-chart-ver": {{ .Chart.Version }}
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    app: redis-enterprise
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-enterprise-crds
  annotations:
    "redis/operator-ver": {{ .Values.operator.image.tag }}
    "redis/helm-chart-ver": {{ .Chart.Version }}
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    app: redis-enterprise
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-enterprise-crds
subjects:
  - kind: ServiceAccount
    name: redis-enterprise-crds
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-enterprise-crds
  namespace: {{ .Release.Namespace }}
  annotations:
    "redis/operator-ver": {{ .Values.operator.image.tag }}
    "redis/helm-chart-ver": {{ .Chart.Version }}
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    app: redis-enterprise
