apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-enterprise-operator
  labels:
    app: redis-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-enterprise-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: redis-enterprise-operator
        app: redis-enterprise
    spec:
      serviceAccountName: redis-enterprise-operator
      containers:
        - name: redis-enterprise-operator
          image: registry.connect.redhat.com/redislabs/redis-enterprise-operator:6.4.2-6
          securityContext:
            runAsUser: 1001
          command:
          - operator-root
          - operator
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: operator-environment-config
                optional: true
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: redis-enterprise-operator
            - name: DEPLOY_RHEL
              value: "true"
          resources:
            limits:
              cpu: 4000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
        - name: admission
          image: registry.connect.redhat.com/redislabs/redis-enterprise-operator:6.4.2-6
          command:
          - operator-root
          - admission
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: operator-environment-config
                optional: true
          ports:
            - containerPort: 8443
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
            initialDelaySeconds: 15
            httpGet:
              path: /liveness
              port: 8443
              scheme: HTTPS