name: Release Charts

on:
  push:
    branches:
      - oshribr-create-github-repo-for-publishing-charts-RED-98120

jobs:
  release:
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"  
      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.2

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ github.token }}"

  generate-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit the generated file
    needs: 
      - release
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: debug-print
        run: |
          echo "Current directory is $(pwd)"
          echo "Contents of the directory are $(ls -la)"
          echo "Contents of the directory are $(ls -la /home/runner/work/helm-release/helm-release/)"

      - name: Generate Helm Charts HTML
        uses: ./.github/actions/generate-helm-html-index
        with:
          index-file: 'index.yaml'
          output-file: 'index.html'
      
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update Helm charts page" || exit 0  # Don't fail if no changes
          git push